export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_POST_ADD = "GET_POST_ADD";
export const GET_POST_ADD_SUCCESS = "GET_POST_ADD_SUCCESS";
export const GET_POST_ADD_FAIL = "GET_POST_ADD_FAIL";

export const GET_POST_EDIT = "GET_POST_EDIT";
export const GET_POST_EDIT_SUCCESS = "GET_POST_EDIT_SUCCESS";
export const GET_POST_EDIT_FAIL = "GET_POST_EDIT_FAIL";

export const GET_POST_DELETE = "GET_POST_DELETE";
export const GET_POST_DELETE_SUCCESS = "GET_POST_DELETE_SUCCESS";
export const GET_POST_DELETE_FAIL = "GET_POST_DELETE_FAIL";
